-- Dados de exemplo do Sistema PAS Marista.
-- Gerado a partir de seed() em js/dados.js — mantenha os dois em passo.
-- Recria o conteúdo de demonstração na prova da 1ª série; as outras três
-- provas nascem vazias, como ficam de verdade até a coordenação começar.

-- Ordem de exclusão: o que aponta por chave estrangeira sai primeiro.
delete from public.respostas;
delete from public.alocacoes;
delete from public.prova_estudantes;
delete from public.itens;
delete from public.textos;
delete from public.estudantes;

insert into public.provas (id, dados) values ('pr-9ano', '{"id":"pr-9ano","ordem":0,"serie":"9º ano","nome":"Simulado PAS 2026","etapa":"1ª Etapa","dataAplicacao":"","duracao":"4h30","totalQuestoes":90,"temRedacao":true,"imprimirRedacao":true}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.provas (id, dados) values ('pr-1em', '{"id":"pr-1em","ordem":1,"serie":"1ª série EM","nome":"Simulado PAS 2026","etapa":"1ª Etapa","dataAplicacao":"2026-09-12","duracao":"4h30","totalQuestoes":null,"temRedacao":true,"imprimirRedacao":true}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.provas (id, dados) values ('pr-2em', '{"id":"pr-2em","ordem":2,"serie":"2ª série EM","nome":"Simulado PAS 2026","etapa":"1ª Etapa","dataAplicacao":"","duracao":"4h30","totalQuestoes":null,"temRedacao":true,"imprimirRedacao":true}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.provas (id, dados) values ('pr-3em', '{"id":"pr-3em","ordem":3,"serie":"3ª série EM","nome":"Simulado PAS 2026","etapa":"1ª Etapa","dataAplicacao":"","duracao":"4h30","totalQuestoes":null,"temRedacao":true,"imprimirRedacao":true}'::jsonb) on conflict (id) do update set dados = excluded.dados;

insert into public.textos (id, dados) values ('tx1', '{"id":"tx1","numero":1,"status":"aprovado","sugeridoPor":null,"titulo":"“O Cerrado e as veredas” — Guimarães Rosa (adapt.)","fonte":"Guimarães Rosa (adaptado)","slots":8,"regra":"regra do coordenador: sem itens tipo D neste texto","linhas":["O buriti é a palmeira dos brejos, das veredas, onde a água","aflora e o chão se faz úmido o ano inteiro. Ali, entre capões","e chapadões, o sertão guarda suas nascentes como quem","guarda segredo antigo.","As veredas alimentam os rios que descem para todas as","bacias do país, e por isso o Cerrado é chamado de","caixa-d’água do Brasil.","Mas a caixa-d’água racha: onde a vereda seca, o buriti","tomba, e com ele vai-se a memória da água."],"provaId":"pr-1em"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.textos (id, dados) values ('tx2', '{"id":"tx2","numero":2,"status":"aprovado","sugeridoPor":null,"titulo":"Infográfico — matriz energética brasileira 2025","fonte":"EPE — Balanço Energético Nacional (adaptado)","slots":6,"regra":"","linhas":["O infográfico apresenta a participação das fontes na matriz","energética brasileira em 2025: hidráulica 52%, eólica 14%,","solar 9%, biomassa 8%, gás natural 9%, carvão 3%,","nuclear 2% e petróleo 3%.","As fontes renováveis somam 83% da geração elétrica,","colocando o Brasil entre as matrizes mais limpas do mundo."],"provaId":"pr-1em"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.textos (id, dados) values ('tx3', '{"id":"tx3","numero":null,"status":"sugestao","sugeridoPor":"João Pedro (História)","titulo":"Sugestão de texto — “Carta da Terra” (trecho)","fonte":"ONU, 2000","slots":6,"regra":"","linhas":["Estamos diante de um momento crítico na história da Terra,","numa época em que a humanidade deve escolher o seu futuro.","À medida que o mundo torna-se cada vez mais interdependente","e frágil, o futuro enfrenta, ao mesmo tempo, grandes perigos","e grandes promessas."],"provaId":"pr-1em"}'::jsonb) on conflict (id) do update set dados = excluded.dados;

insert into public.itens (id, dados) values ('it1', '{"id":"it1","textoId":"tx1","tipo":"A","componente":"Literatura","autor":"Ana Beatriz","habilidade":"H2 — Recursos expressivos","grupo":"Interpretar","versao":"ambas","linhasRef":"1-4","gabarito":"C","opcoes":[],"enunciado":"No fragmento, a personificação do sertão (linhas 3 e 4) reforça o tom lírico característico da prosa de Guimarães Rosa.","status":"aprovado","comentarios":[],"provaId":"pr-1em","ordem":0}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it2', '{"id":"it2","textoId":"tx1","tipo":"A","componente":"Geografia","autor":"Túlio","habilidade":"H14 — Dinâmica hídrica","grupo":"Interpretar","versao":"ambas","linhasRef":"5-7","gabarito":"C","opcoes":[],"enunciado":"A expressão “caixa-d’água do Brasil” refere-se ao papel do Cerrado na recarga dos aquíferos e das bacias hidrográficas do país.","status":"aprovado","comentarios":[],"provaId":"pr-1em","ordem":1}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it3', '{"id":"it3","textoId":"tx1","tipo":"C","componente":"Biologia","autor":"Fernanda","habilidade":"H18 — Adaptações vegetais","grupo":"Executar","versao":"regular","linhasRef":"1-2","gabarito":"B","opcoes":["raízes pneumatóforas ausentes em solos alagados","tolerância ao encharcamento permanente do solo","caducifolia acentuada na estação chuvosa","súber espesso como adaptação exclusiva ao fogo"],"enunciado":"Considerando a fitofisionomia descrita no texto, assinale a opção correta acerca das adaptações do buriti.","status":"aprovado","comentarios":[],"provaId":"pr-1em","ordem":2}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it4', '{"id":"it4","textoId":"tx1","tipo":"A","componente":"Biologia","autor":"Fernanda","habilidade":"H6 — Inferências","grupo":"Executar","versao":"ambas","linhasRef":"5-7","gabarito":"C","opcoes":[],"enunciado":"Com base nas linhas 5 a 7, julgue o item: as veredas funcionam como zonas de recarga hídrica, e sua supressão reduz a vazão de base dos rios que nascem no Cerrado.","status":"area","comentarios":[{"autor":"Túlio","papel":"coord. de área (Ciências da Natureza)","quando":"ontem, 14h32","texto":"Fernanda, o termo “compromete a vazão” pode gerar dupla interpretação com chuva regional. Sugiro fechar em “reduz a vazão de base dos rios”."},{"autor":"Fernanda","papel":"docente","quando":"hoje, 8h15","texto":"Boa! Ajustei o enunciado conforme sugerido. Pode reavaliar?"}],"provaId":"pr-1em","ordem":3}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it5', '{"id":"it5","textoId":"tx1","tipo":"B","componente":"Matemática","autor":"Carlos Eduardo","habilidade":"H21 — Grandezas proporcionais","grupo":"Executar","versao":"ambas","linhasRef":"5-7","gabarito":"960","opcoes":[],"enunciado":"Se a vazão média de uma nascente é de 12 L/min, calcule, em litros, o volume acumulado em 1h20min.","status":"aprovado","comentarios":[],"provaId":"pr-1em","ordem":4}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it6', '{"id":"it6","textoId":"tx2","tipo":"A","componente":"Física","autor":"Marina","habilidade":"H25 — Transformação de energia","grupo":"Criticar","versao":"regular","linhasRef":"1-4","gabarito":"E","opcoes":[],"enunciado":"De acordo com o infográfico, a energia nuclear responde pela maior parcela da matriz elétrica brasileira.","status":"rascunho","comentarios":[],"provaId":"pr-1em","ordem":5}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it7', '{"id":"it7","textoId":"tx2","tipo":"B","componente":"Matemática","autor":"Carlos Eduardo","habilidade":"H22 — Porcentagem","grupo":"Planejar","versao":"regular","linhasRef":"1-5","gabarito":"830","opcoes":[],"enunciado":"Considerando que as fontes renováveis somam 83% da geração, calcule, em décimos percentuais, essa participação (ex.: 83,0% → 830).","status":"geral","comentarios":[{"autor":"Raul","papel":"coordenação geral","quando":"hoje, 9h02","texto":"Aprovado na área. Verificar apenas se o comando “décimos percentuais” está claro para a 2ª série."}],"provaId":"pr-1em","ordem":6}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.itens (id, dados) values ('it8', '{"id":"it8","textoId":"tx2","tipo":"D","componente":"História","autor":"João Pedro","habilidade":"H10 — Argumentação","grupo":"Criticar","versao":"regular","linhasRef":"5-6","opcoes":[],"dLinhas":8,"dPauta":true,"gabarito":"Espera-se que o estudante reconheça a alta participação renovável como argumento favorável e aponte uma limitação (sazonalidade hídrica, intermitência eólica/solar ou impactos socioambientais de hidrelétricas).","enunciado":"Com base no infográfico, avalie em que medida a matriz elétrica brasileira pode ser considerada “limpa”, apresentando um argumento favorável e uma limitação.","status":"aprovado","comentarios":[],"provaId":"pr-1em","ordem":7}'::jsonb) on conflict (id) do update set dados = excluded.dados;

insert into public.estudantes (id, dados) values ('e1', '{"id":"e1","nome":"Antonia Silva","matricula":"2026-0142","turma":"1ª B","versao":"regular","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.estudantes (id, dados) values ('e2', '{"id":"e2","nome":"Bruno Carvalho","matricula":"2026-0077","turma":"1ª A","versao":"regular","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.estudantes (id, dados) values ('e3', '{"id":"e3","nome":"Clara Nogueira","matricula":"2026-0119","turma":"1ª B","versao":"regular","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.estudantes (id, dados) values ('e4', '{"id":"e4","nome":"Davi Sampaio","matricula":"2026-0205","turma":"1ª C","versao":"regular","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.estudantes (id, dados) values ('e5', '{"id":"e5","nome":"Elisa Fontes","matricula":"2026-0231","turma":"1ª D","versao":"adaptada","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;
insert into public.estudantes (id, dados) values ('e6', '{"id":"e6","nome":"Felipe Arruda","matricula":"2026-0058","turma":"1ª A","versao":"regular","serie":"1ª série EM"}'::jsonb) on conflict (id) do update set dados = excluded.dados;

insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e1') on conflict do nothing;
insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e2') on conflict do nothing;
insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e3') on conflict do nothing;
insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e4') on conflict do nothing;
insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e5') on conflict do nothing;
insert into public.prova_estudantes (prova_id, est_id) values ('pr-1em', 'e6') on conflict do nothing;

insert into public.respostas (prova_id, est_id, dados) values ('pr-1em', 'e1', '{"marcacoes":{"it1":"C","it2":"C","it3":"B","it5":"960"},"discursivas":{"it8":8.5},"redacao":{"nc":9,"ne":3,"tl":28}}'::jsonb) on conflict (prova_id, est_id) do update set dados = excluded.dados;
insert into public.respostas (prova_id, est_id, dados) values ('pr-1em', 'e2', '{"marcacoes":{"it1":"C","it2":"E","it3":"D","it5":"720"},"discursivas":{},"redacao":{"nc":7.5,"ne":6,"tl":30}}'::jsonb) on conflict (prova_id, est_id) do update set dados = excluded.dados;
insert into public.respostas (prova_id, est_id, dados) values ('pr-1em', 'e3', '{"marcacoes":{"it1":"E","it2":"C","it3":"B","it5":"960"},"discursivas":{"it8":6},"redacao":{"nc":8,"ne":2,"tl":25}}'::jsonb) on conflict (prova_id, est_id) do update set dados = excluded.dados;
